version: "3.1"


services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=$PGPASS
      - POSTGRES_USER=$PGUSER
      - TZ=GMT+2
      - PGTZ=GMT+2
    restart: always
    ports:
      - 5432:5432
    networks:
      - alfredbot
    volumes:
      - ./:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - alfredbot
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db




networks:
  alfredbot:
    driver: bridge

