version: "3.1"


services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - alfredbot
    volumes:
      - ./:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - alfredbot
    volumes:
      - .:/src
    depends_on:
      - db




networks:
  alfredbot:
    driver: bridge

